# Generated by Django 4.2.2 on 2023-06-24 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_usersprofile_name"),
        ("chaty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Massage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1024)),
                ("time", models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(auto_created=True, max_length=64, unique=True),
                ),
                ("is_private", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.AddField(
            model_name="massage",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="massage",
                to="chaty.room",
            ),
        ),
        migrations.AddField(
            model_name="massage",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="user.usersprofile",
            ),
        ),
    ]
