# Generated by Django 4.2.2 on 2023-06-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaty", "0002_massage_room_delete_group_massage_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massage",
            name="content",
            field=models.TextField(max_length=64),
        ),
    ]
