# Generated by Django 4.2.2 on 2023-06-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaty", "0003_alter_massage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="massage",
            name="content",
            field=models.TextField(max_length=1024),
        ),
    ]
