# Generated by Django 4.2.2 on 2023-06-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chaty", "0005_alter_massage_options_room_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="member",
        ),
    ]
