# Generated by Django 4.2.2 on 2023-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersprofile",
            name="name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
