# Generated by Django 4.2.2 on 2023-06-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaty", "0002_massage_room_delete_group_massage_destination_and_more"),
        ("user", "0002_usersprofile_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Foo",
        ),
        migrations.AddField(
            model_name="usersprofile",
            name="rooms",
            field=models.ManyToManyField(related_name="member", to="chaty.room"),
        ),
    ]
