# Generated by Django 4.2.2 on 2023-06-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_delete_foo_usersprofile_rooms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersprofile",
            name="rooms",
        ),
    ]
